<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Agree and accept Service Agreement and Privacy Policy' => '',
    'Agree and accept {serviceAgreement} and {privacyPolicy}' => '',
    'Army ID' => '',
    'Authentication' => '',
    'Choose file' => '',
    'Created At' => '',
    'Email' => '',
    'Failed Reason' => '',
    'Failure reason:' => '',
    'File has to be smaller than 2MB' => '',
    'Full Name' => '',
    'HKMC ID' => '',
    'ID Card' => '',
    'Id Card' => '',
    'Id Card Image' => '',
    'Id Type' => '',
    'Passport ID' => '',
    'Passport cover' => '',
    'Passport person page' => '',
    'Passport self holding' => '',
    'Privacy Policy' => '',
    'Service Agreement' => '',
    'Sorry, after passing your review, the information you submitted has not been approved. Please check the information and submit it again.' => '',
    'Status' => '',
    'Submit' => '',
    'Taiwan ID' => '',
    'Updated At' => '',
    'User Id' => '',
    'Verify Code' => '',
    'Your application is submitted successfully! We will be processed within three working days, the results will be processed by mail, station message to inform you, if in doubt please contact the official administrator.' => '',
    '{attribute} must be selected.' => '',
];
